# Base configs
baseurl: "https://tariqphotography.in"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Tariq"
subtitle: "See the world through my eyes!"
author: "Tariq"
header:
 title: "Photography"
 subtitle: "by Tariq"
footer:
 name: "Hey there, my name is Tariq"
 bio: "I am ______ and have good skills in photography."
 github: "Want a photoshoot? Just <a href = "mailto: tariq@example.com">send a mail</a> ;)"
web_design: "<a href = "mailto: krishnaprasanth.g@gmail.com">Prasanth G</a> and made possible by <a href="https://github.com/rampatra/photography">AJ</a>"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  instagram: "https://www.instagram.com/ram_patra"
  linkedin: "https://in.linkedin.com/in/ram-patra"